<?php
/**
 * Dead Signal Studio — backend configuration, example.
 *
 * setup.php writes this file for you. Copy it to env.php by hand only if you
 * would rather configure the studio without the wizard — the schema still has
 * to be applied afterwards, which setup.php also does (or `php server/migrate.php`
 * from the command line).
 *
 * NEVER commit env.php: it holds the database password.
 */
return [
    'app' => [
        'name'  => 'Dead Signal Studio',

        // Debug puts exception messages in API responses. Development only —
        // on a live host it hands an attacker your file paths and SQL.
        'debug' => false,

        'timezone' => 'UTC',

        // How long a sign-in lasts, in seconds. A week by default: being signed
        // out mid-edit is the kind of small hostility that makes people stop
        // using a tool. /auth/me extends it, so an active session does not die.
        'session_lifetime' => 604800,

        // Only turn this on behind a proxy you control. X-Forwarded-For is
        // client-supplied, and trusting it on a directly-exposed host lets
        // anyone rotate their apparent IP and walk past the rate limit.
        'trust_proxy'      => false,
        'trust_proxy_hops' => 1,
    ],

    'database' => [
        'driver'   => 'mysql',
        'host'     => 'localhost',
        'port'     => 3306,
        'database' => 'studio',
        'username' => 'studio',
        'password' => '',
        'charset'  => 'utf8mb4',
    ],

    'rate_limit' => [
        'enabled' => true,
        // Relative to this file, so it survives the hosting account being moved
        // or renamed — a baked-in absolute path does not.
        'storage_path' => __DIR__ . '/data/rate_limits',
    ],

    // Proves server access when re-running setup.php on a configured install.
    // Generated by the wizard; only needed here if the database password is
    // empty (socket auth), which would otherwise leave nothing to check against.
    'setup' => [
        'secret' => '',
    ],
];
